version: "3.8"

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/src

  kafka_to_pg_worker:
    build: .
    restart: always
    command: python -u workers/kafka_to_pg_logs.py 
    ports:
      - 9965:9965
    volumes:
      - .:/src

  pg_to_kafka_worker:
      build: .
      restart: always
      command: python -u workers/pg_to_kafka.py 
      volumes:
        - .:/src